### ISSUE TITLE
Update Expressions forbidden on signed attributes

### ISSUE THREAD

**Issue by alebastrov** [aws/aws-database-encryption-sdk-dynamodb-java#297]
I am trying to use encryption v3 in DynamoDb
I created/prepared interceptor and I'm calling dynamodbClient.updateItem() how it is shown below
~~~
UpdateItemRequest.Builder updateItemRequest = UpdateItemRequest.builder()
            .tableName( key.getTableName() )
            .key( getKeyAttribute( key ) )
            .updateExpression( updateExpression )
            .expressionAttributeValues( updatedValues );
UpdateItemResponse response = dynamoDbClient.updateItem( updateItemRequest.build() );
~~~
where 
- key is 'longId -> {AttributeValue@10273} "AttributeValue(S=xMDcFeqgJunlmrTNMzre+aXysQvPtVKpbmxN1ZaqT3k=)"'
- updateExpression is 'SET v1 = :var1'
- updatedValues are ':var1 -> {AttributeValue@10280} "AttributeValue(BOOL=false)"' 

My attribute 'v1' has defined CryptoAction.ENCRYPT_AND_SIGN (of course 'longId' has  CryptoAction.SIGN_ONLY as it's a key)
Note: type of v1 is boolean, though setting it to string does not change anything.

and this is throwing an exception:
~~~
software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.model.DynamoDbEncryptionTransformsException: Update Expressions forbidden on signed attributes : v1
	at software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.model.DynamoDbEncryptionTransformsException$BuilderImpl.build(DynamoDbEncryptionTransformsException.java:104)
	at software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.ToNative.Error(ToNative.java:89)
	at software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.ToNative.Error(ToNative.java:94)
	at software.amazon.cryptography.dbencryptionsdk.dynamodb.transforms.DynamoDbEncryptionTransforms.UpdateItemInputTransform(DynamoDbEncryptionTransforms.java:325)
	at software.amazon.cryptography.dbencryptionsdk.dynamodb.DynamoDbEncryptionInterceptor.modifyRequest(DynamoDbEncryptionInterceptor.java:178)
	at oap.storage.dynamo.client.DefaultEncryptionInterceptor.modifyRequest(DefaultEncryptionInterceptor.java:40)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyRequest(ExecutionInterceptorChain.java:68)
	at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.runInitialInterceptors(AwsExecutionContextBuilder.java:176)
	at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.invokeInterceptorsAndCreateExecutionContext(AwsExecutionContextBuilder.java:112)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.invokeInterceptorsAndCreateExecutionContext(AwsSyncClientHandler.java:69)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:78)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.updateItem(DefaultDynamoDbClient.java:6515)
~~~

I see in test 'TestUpdateItemInputUpdateExpressionEncrypted' that this case is forbidden (UpdateExpression := Some("SET encrypt = :p"),)
but my question is how to work this around?

UPD: If I did not set 'updateExpression' in UpdateItemRequest then I would get exception
~~~
software.amazon.awssdk.services.dynamodb.model.DynamoDbException: Invalid UpdateExpression: The expression can not be empty; (Service: DynamoDb, Status Code: 400, Request ID: d95fddc9-5178-4a8e-924d-ddff759d8cf3)
...
~~~

**Comment by justplaz** [comment]
Hi,

Thanks for reaching out! 
This case is forbidden because the signature for the field is calculated over the entire item. 
If you only change one attribute, the signature is not recalculated, and subsequent decryption attempts will fail because the signature is now invalid. 

The workaround is to use `putItem` (or its semantic equivalents) for all write operations, as this will recalculate the signature using each attribute value. 
Feel free to re-open if you have further questions.

**Comment by alebastrov** [comment]
so atomic update is not possible as well?
I mean
'SET #ver #ver+1'

**Comment by texastony** [comment]
@alebastrov 
Atomic Writes are permitted. 
You would use `PutItem` with a Condition Expression.
The Condition statement asserts the item is as expected.
The Put then re-writes the item, along with it's signature. 
See [DynamoDB's `PutItem` Documentation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html#API_PutItem_RequestSyntax).

In your case, the Condition Expression would assert that the record's version is 1 less than the version that will be written.

**Comment by texastony** [comment]
@alebastrov

The [response above](https://github.com/aws/aws-database-encryption-sdk-dynamodb-java/issues/297#issuecomment-1668278287) requires a Get before the Put,
as no update expression is used.

That is appropriate for Attributes that are Signed,
but it is NOT an Atomic Update.

The record must entirely be retrieved,
decrypted, modified,
re-encrypted, calculating a new signature,
and then re-written to the table with the conditional expression.

Should the Put request fail due to the condition expression,
i.e: the version was increment by another client,
the process will need to be repeated with the correct value
(assuming the version MUST BE incremented).

But if the attribute being updated is NOT SIGNED,
you can use an update expression,
allowing for a true Atomic Update. 

In our [BasicPutGetExample](https://github.com/aws/aws-database-encryption-sdk-dynamodb-java/blob/main/Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/BasicPutGetExample.java#L58),
you can see that `:attribute3` is configured to NOT be Signed
(via `CryptoAction.DO_NOTHING`).

Here is the [same effect for the DynamoDB Enhanced Client via Annotations](https://github.com/aws/aws-database-encryption-sdk-dynamodb-java/blob/main/Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/enhanced/SimpleClass.java#L60-L68).

As long as the update expression only effects attributes that are "Do Nothing", 
the DB-ESDK will not throw "Invalid UpdateExpression".
